version: '3.8'

services:
  rabbitmq-devtrackr:
    image: rabbitmq:3-management
    container_name: rabbitmq-devtrackr
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - devtrackr-net

  auth-db-devtrackr:
    image: postgres:15
    container_name: auth-db-devtrackr
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: authdb
    ports:
      - "5434:5432"
    volumes:
      - devtrackr_auth_pgdata:/var/lib/postgresql/data
    networks:
      - devtrackr-net

  user-db-devtrackr:
    image: postgres:15
    container_name: user-db-devtrackr
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: userdb
    ports:
      - "5435:5432"
    volumes:
      - devtrackr_user_pgdata:/var/lib/postgresql/data
    networks:
      - devtrackr-net

  authservice-devtrackr:
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    container_name: authservice-devtrackr
    depends_on:
      - auth-db-devtrackr
      - rabbitmq-devtrackr
    environment:
      - ConnectionStrings__DefaultConnection=Host=auth-db-devtrackr;Port=5432;Database=authdb;Username=admin;Password=admin123
    ports:
      - "5101:8080"
    networks:
      - devtrackr-net

  userservice-devtrackr:
    build:
      context: .
      dockerfile: UserService/Dockerfile
    container_name: userservice-devtrackr
    depends_on:
      - user-db-devtrackr
    environment:
      - ConnectionStrings__DefaultConnection=Host=user-db-devtrackr;Port=5432;Database=userdb;Username=admin;Password=admin123
    ports:
      - "5102:8080"
    networks:
      - devtrackr-net

  activityservice-devtrackr:
    build:
      context: .
      dockerfile: ActivityService/Dockerfile
    container_name: activityservice-devtrackr
    ports:
      - "5200:8080"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    networks:
      - devtrackr-net


  task-db-devtrackr:
    image: postgres:15
    container_name: task-db-devtrackr
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: taskdb
    ports:
      - "5436:5432"
    volumes:
      - devtrackr_task_pgdata:/var/lib/postgresql/data
    networks:
      - devtrackr-net

  taskservice-devtrackr:
    build:
      context: .
      dockerfile: TaskService/Dockerfile
    container_name: taskservice-devtrackr
    depends_on:
      - task-db-devtrackr
    environment:
      - ConnectionStrings__DefaultConnection=Host=task-db-devtrackr;Port=5432;Database=taskdb;Username=admin;Password=admin123
    ports:
      - "5103:8080"
    networks:
      - devtrackr-net


volumes:
  devtrackr_auth_pgdata:
  devtrackr_user_pgdata:
  devtrackr_task_pgdata:


networks:
  devtrackr-net:
    driver: bridge
